apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: app-kubernetes-namespace
spec:
  selector:
    app: backend-express
  type: ClusterIP
  ports:
    - port: 5000 # Backend service port
      targetPort: 5000 # Backend container port