apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-secret
  namespace: app-kubernetes-namespace
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA== # root
  MYSQL_DATABASE: bWFpbi1rdWJlcg== # main-kuber
  MYSQL_USER: dXNlcg== # user
  MYSQL_PASSWORD: cGFzc3dvcmQ= # password

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: port-config
  namespace: app-kubernetes-namespace
data:
  PORT_MYSQL: "3306"
  NEXT_PUBLIC_PORT_BACKEND: "5000"
  MYSQL_HOST_SERVICE: "mysql-db-service"
  NEXT_PUBLIC_BACKEND_HOST_SERVICE: "backend-service"